version: '3.8'

services:
  nusatalk:
    build: .
    container_name: nusatalk-container
    ports:
      - '5173:5173'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: ['npm', 'run', 'dev']
